modLoader="javafml"
loaderVersion="[24,]"
issueTrackerURL="https://github.com/neoforged/NeoForge/issues"
logoFile="neoforged_logo.png"
license="LGPL v2.1"

[[mods]]
    modId="neoforge"
    # We use the global forge version
    version="${global.forgeVersion}"
    updateJSONURL="https://maven.neoforged.net/releases/net/neoforged/forge/promotions_slim.json"
    displayName="NeoForge"
    credits="Anyone who has contributed on Github and supports our development"
    authors="The NeoForged Team"
    description='''
    NeoForge, a NEW broad compatibility API.
    '''


[[mods]]
modId="forge"
# We use the global forge version
version="47.1.3"
displayName="Forge Compatibility"
description='''
    Required for compatibility with existing Forge versions
    '''